region = "ap-south-1"
name   = "testusers"
path                 = "/"
force_destroy        = true
pgp_key              = "keybase:d3_jain"
permissions_boundary = "arn:aws:iam::aws:policy/ReadOnlyAccess"
tags                 = {}
policy_name          = "Test_Policy"
description          = "My Test Policy"
profile              = "ArulSaxena"
name_prefix          = null
file_name            = ["policy_x", "policy_y", "policy_z"]